swagger: '2.0'
info:
  description: Communication with Slack API
  version: '1'
  title: Slack API
host: localhost:10010
basePath: /
schemes:
  - https
paths:
  /deleteMsg:
    x-swagger-router-controller: deleteMsg
    post:
      operationId: deleteMsg
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          required: false
          schema:
            properties:
              channel:
                type: string
              ts:
                type: string
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/jsonResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse" 
  /deleteMsg/scheduled:
    x-swagger-router-controller: deleteMsgScheduled
    post:
      operationId: deleteMsgScheduled
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          required: false
          schema:
            properties:
              channel:
                type: string
              scheduledMessageId:
                type: string
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/jsonResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse" 
  /getPermalink:
    x-swagger-router-controller: getPermalink
    post:
      operationId: getPermalink
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          required: false
          schema:
            properties:
              channel:
                type: string
              messageTs:
                type: string
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/jsonResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse" 
  /sendMsg:
    x-swagger-router-controller: sendMsg
    post:
      operationId: sendMsg
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          required: false
          schema:
            properties:
              channel:
                type: string
              text:
                type: string
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/jsonResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse" 
  /sendMsg/Button:
    x-swagger-router-controller: sendMsg
    post:
      operationId: sendMsgButton
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          required: false
          schema:
            properties:
              channel:
                type: string
              text:
                type: string
              callbackId:
                type: string 
              textButtons:
                type: array
                items:
                  type: string
              style:
                type: array
                items:
                  type: string
              textConfirmation:
                type: array
                items:
                  type: string
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/jsonResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse" 
  /sendMsg/ephemeral:
    x-swagger-router-controller: sendMsgEphemeral
    post:
      operationId: sendMsgEphemeral
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          required: false
          schema:
            properties:
              channel:
                type: string
              user:
                type: string
              text:
                type: string
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/jsonResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse" 
  /sendMsg/ephemeral/Button:
    x-swagger-router-controller: sendMsgEphemeral
    post:
      operationId: sendMsgEphemeralButton
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          required: false
          schema:
            properties:
              channel:
                type: string
              text:
                type: string
              user:
                type: string
              callbackId:
                type: string 
              textButtons:
                type: array
                items:
                  type: string
              style:
                type: array
                items:
                  type: string
              textConfirmation:
                type: array
                items:
                  type: string
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/jsonResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse" 
  /sendMsg/schedule:
    x-swagger-router-controller: sendMsgSchedule
    post:
      operationId: sendMsgSchedule
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          required: false
          schema:
            properties:
              channel:
                type: string
              postAt:
                type: string
              text:
                type: string
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/jsonResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse" 
  /sendMsg/schedule/Button:
    x-swagger-router-controller: sendMsgschedule
    post:
      operationId: sendMsgScheduleButton
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          required: false
          schema:
            properties:
              channel:
                type: string
              postAt:
                type: string
              text:
                type: string
              callbackId:
                type: string 
              textButtons:
                type: array
                items:
                  type: string
              style:
                type: array
                items:
                  type: string
              textConfirmation:
                type: array
                items:
                  type: string
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/jsonResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse" 
  /updateMsg:
    x-swagger-router-controller: updateMsg
    post:
      operationId: updateMsg
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          required: false
          schema:
            properties:
              channel:
                type: string
              text:
                type: string
              ts:
                type: string
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/jsonResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse" 
  /updateMsg/Button:
    x-swagger-router-controller: updateMsg
    post:
      operationId: updateMsgButton
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          required: false
          schema:
            properties:
              channel:
                type: string
              text:
                type: string
              ts:
                type: string
              callbackId:
                type: string 
              textButtons:
                type: array
                items:
                  type: string
              style:
                type: array
                items:
                  type: string
              textConfirmation:
                type: array
                items:
                  type: string
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/jsonResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse" 
  /sendOverflow/static:
    x-swagger-router-controller: sendOverflow
    post:
      operationId: sendOverflowStatic
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          required: false
          schema:
            properties:
              channel:
                type: string
              boldHeadline:
                type: string
              headlineLeftField:
                type: array
                items:
                  type: string
              headlineRightField:
                type: array
                items:
                  type: string
              actionId:
                type: array
                items:
                  type: string
              textOptions:
                type: array
                items:
                  type: string
              changes:
                type: string
              message:
                type: string
              buttonName:
                type: string
              buttonValue:
                type: string
              buttonActionId:
                type: string
              buttonMessage:
                type: string    
              type:
                type: array
                items:
                  type: string
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/jsonResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse" 
  /updateOverflow:
    x-swagger-router-controller: updateOverflow
    post:
      operationId: updateOverflow
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          required: false
          schema:
            properties:
              channel:
                type: string
              ts:
                type: string
              blocks:
                type: string
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/jsonResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse" 
  /startDialog:
    x-swagger-router-controller: startDialog
    post:
      operationId: startDialog
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          required: false
          schema:
            properties:
              triggerid:
                type: string
              callbackId:
                type: string
              title:
                type: string
              label:
                type: array
                items:
                  type: string
              name:
                type: array
                items:
                  type: string
              placeholder:
                type: array
                items:
                  type: string
              data_source:
                type: array
                items:
                  type: string
              options:
                type: array
                items:
                  type: string
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/jsonResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse" 
  /sendFile:
    x-swagger-router-controller: sendFile
    post:
      operationId: sendFile
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          required: false
          schema:
            properties:
              channel:
                type: string
              fileName:
                type: string
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/jsonResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse" 
  /slackreceive:
    x-swagger-router-controller: slackReceive
    post:
      description: slack request handling
      operationId: slackReceive
      consumes:
        - application/x-www-form-urlencoded
      produces:
        - application/json
      parameters:
        - in: formData
          name: payload
          description: payload
          required: true
          type: string
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/jsonResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /slackGet/conversations:
    x-swagger-router-controller: slackGet
    get:
      operationId: slackGetConversations
      consumes:
        - application/x-www-form-urlencoded
      parameters: []
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/jsonResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"       
  /camunda/startProcess/schulungOrganisieren:
    x-swagger-router-controller: camundaStartProcess
    post:
      operationId: camundaStartProcessSchulungOrganisieren
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          required: false
          schema:
            properties:
              name:
                type: string
              trainer:
                type: string
              date:
                type: string 
              room:
                type: string
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/jsonResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse" 
  /camunda/sendMessage:
    x-swagger-router-controller: camundaSendMessage
    post:
      operationId: camundaSendMessage
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          required: false
          schema:
            properties:
              nameVariable:
                type: array
                items:
                  type: string
              variable:
                type: array
                items:
                  type: string
              message:
                type: string  
              correlationKey:
                type: string
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/jsonResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse" 
  /camunda/instance/getId:
    x-swagger-router-controller: camundaInstance
    get:
      operationId: camundaInstanceGetId
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          required: false
          schema:
            properties:
              correlationKey:
                type: string
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/jsonResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse" 
  /camunda/instance/deleteVariable:
    x-swagger-router-controller: camundaInstance
    get:
      operationId: camundaInstanceDeleteVariable
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          required: false
          schema:
            properties:
              instanceId:
                type: string
              variable:
                type: string
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/jsonResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse" 


definitions:
  jsonResponse:
    required:
      - message
    properties:
      message:
        type: string
  ErrorResponse:
    required:
      - message
    properties:
      message:
        type: string



      









